### PR TITLE
ADD CONTAINS

### PR DESCRIPTION
**Pull request by xinity**

### CODE REVIEW

**Comment by l0rd** [comment]
This PR include also the commits of PR #6. Can you please rebase this branch with master ?

**Comment by xinity** [comment]
almost finished :)
need to get ride of "grep -q ! " instead of "! grep -q" and will be fine

**Comment by l0rd** [comment]
Great! Thanks @xinity

**Comment by xinity** [comment]
all right, all fixed except i haven't found how to get rid of "grep -q !" to make it "! grep -q''

i'll update this PR anyway, if you have any clues please let me know.

sorry not having not enough GO skills :(

**Comment by l0rd** [comment]
No problem for the `grep -q !` I will fix it in a separate commit. Thanks for your contribution @xinity!

**Pull request merged**
